# Generated by Django 5.2.7 on 2025-10-19 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='born_place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
