# Generated by Django 5.2.7 on 2025-10-19 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_customer_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='hobby',
            new_name='hobby_1',
        ),
        migrations.AddField(
            model_name='customer',
            name='hobby_2',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
    ]
